namespace: wiz-task

mongoSecret:
  mongoHost: ""
  mongoUser: ""
  mongoPass: ""

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8888
