name: Build and Deploy Tornado WebApp

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "tornado-webapp/**"
      - "tornado-webapp-helm/**"
      - ".github/workflows/deploy-webapp.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: tornado-webapp
  EKS_CLUSTER_NAME: wiz-task-eks
  HELM_RELEASE: tornado-webapp
  HELM_CHART_PATH: ./tornado-webapp-helm
  MONGOHOST: "aXAtMTAtMC0yLTE3Ny5lYzIuaW50ZXJuYWw="
  MONGOUSER: "YWRtaW4="
  MONGOPASS: "YWRtaW5wYXNzd29yZA=="


jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            ./tornado-webapp

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME

      - name: Deploy with Helm
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          helm upgrade --install $HELM_RELEASE $HELM_CHART_PATH \
            --namespace wiz-task --create-namespace \
            --set image.repository=$ECR_REGISTRY/$ECR_REPOSITORY \
            --set image.tag=$IMAGE_TAG \
            --set mongoSecret.mongoHost=$MONGOHOST \
            --set mongoSecret.mongoUser=$MONGOUSER \
            --set mongoSecret.mongoPass=$MONGOPASS