name: Scan Terraform with Checkov

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/scan-terraform.yml"

jobs:
  scan-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Scan Terraform with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform